# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\kursach_project_gomel\forms\ui\AdminTableWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AdminTableWindow(object):
    def setupUi(self, AdminTableWindow):
        AdminTableWindow.setObjectName("AdminTableWindow")
        AdminTableWindow.resize(699, 522)
        self.tableWidget = QtWidgets.QTableWidget(AdminTableWindow)
        self.tableWidget.setGeometry(QtCore.QRect(50, 20, 601, 241))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.InsertButton = QtWidgets.QPushButton(AdminTableWindow)
        self.InsertButton.setGeometry(QtCore.QRect(70, 320, 75, 23))
        self.InsertButton.setObjectName("InsertButton")
        self.pushButton_2 = QtWidgets.QPushButton(AdminTableWindow)
        self.pushButton_2.setGeometry(QtCore.QRect(174, 320, 81, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(AdminTableWindow)
        self.pushButton_3.setGeometry(QtCore.QRect(290, 320, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(AdminTableWindow)
        QtCore.QMetaObject.connectSlotsByName(AdminTableWindow)

    def retranslateUi(self, AdminTableWindow):
        _translate = QtCore.QCoreApplication.translate
        AdminTableWindow.setWindowTitle(_translate("AdminTableWindow", "Dialog"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("AdminTableWindow", "Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("AdminTableWindow", "Birthday"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("AdminTableWindow", "Games"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("AdminTableWindow", "Goals"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("AdminTableWindow", "Assists"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("AdminTableWindow", "Points"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("AdminTableWindow", "Penalty Minutes"))
        self.InsertButton.setText(_translate("AdminTableWindow", "Add Player"))
        self.pushButton_2.setText(_translate("AdminTableWindow", "Update Player"))
        self.pushButton_3.setText(_translate("AdminTableWindow", "Delete Player"))
