# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\kursach_project_gomel\forms\ui\InsertWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(750, 500)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(270, 50, 171, 31))
        font = QtGui.QFont()
        font.setFamily("News706 BT")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.name_field = QtWidgets.QLineEdit(Dialog)
        self.name_field.setGeometry(QtCore.QRect(70, 160, 200, 40))
        self.name_field.setStyleSheet("background-color: rgba(0, 0, 0 0);\n"
"font: 14pt \"MS UI Gothic\";\n"
"border:1px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:rgba(46, 82, 101, 255);\n"
"color:rgb(255, 255, 255);\n"
"padding-bottom:7px")
        self.name_field.setObjectName("name_field")
        self.birthday_field = QtWidgets.QLineEdit(Dialog)
        self.birthday_field.setGeometry(QtCore.QRect(450, 160, 200, 40))
        self.birthday_field.setStyleSheet("background-color: rgba(0, 0, 0 0);\n"
"font: 14pt \"MS UI Gothic\";\n"
"border:1px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:rgba(46, 82, 101, 255);\n"
"color:rgb(255, 255, 255);\n"
"padding-bottom:7px")
        self.birthday_field.setObjectName("birthday_field")
        self.game_field = QtWidgets.QLineEdit(Dialog)
        self.game_field.setGeometry(QtCore.QRect(70, 280, 200, 40))
        self.game_field.setStyleSheet("background-color: rgba(0, 0, 0 0);\n"
"font: 14pt \"MS UI Gothic\";\n"
"border:1px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:rgba(46, 82, 101, 255);\n"
"color:rgb(255, 255, 255);\n"
"padding-bottom:7px")
        self.game_field.setObjectName("game_field")
        self.goal_field = QtWidgets.QLineEdit(Dialog)
        self.goal_field.setGeometry(QtCore.QRect(70, 340, 200, 40))
        self.goal_field.setStyleSheet("background-color: rgba(0, 0, 0 0);\n"
"font: 14pt \"MS UI Gothic\";\n"
"border:1px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:rgba(46, 82, 101, 255);\n"
"color:rgb(255, 255, 255);\n"
"padding-bottom:7px")
        self.goal_field.setObjectName("goal_field")
        self.assist_field = QtWidgets.QLineEdit(Dialog)
        self.assist_field.setGeometry(QtCore.QRect(440, 280, 200, 40))
        self.assist_field.setStyleSheet("background-color: rgba(0, 0, 0 0);\n"
"font: 14pt \"MS UI Gothic\";\n"
"border:1px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:rgba(46, 82, 101, 255);\n"
"color:rgb(255, 255, 255);\n"
"padding-bottom:7px")
        self.assist_field.setObjectName("assist_field")
        self.penalty_minutes_field = QtWidgets.QLineEdit(Dialog)
        self.penalty_minutes_field.setGeometry(QtCore.QRect(440, 340, 200, 40))
        self.penalty_minutes_field.setStyleSheet("background-color: rgba(0, 0, 0 0);\n"
"font: 14pt \"MS UI Gothic\";\n"
"border:1px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:rgba(46, 82, 101, 255);\n"
"color:rgb(255, 255, 255);\n"
"padding-bottom:7px")
        self.penalty_minutes_field.setObjectName("penalty_minutes_field")
        self.insert_button = QtWidgets.QPushButton(Dialog)
        self.insert_button.setGeometry(QtCore.QRect(240, 400, 240, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.insert_button.setFont(font)
        self.insert_button.setObjectName("insert_button")
        self.back_to_admin_window = QtWidgets.QPushButton(Dialog)
        self.back_to_admin_window.setGeometry(QtCore.QRect(40, 30, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.back_to_admin_window.setFont(font)
        self.back_to_admin_window.setObjectName("back_to_admin_window")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(20, 10, 691, 451))
        self.label_8.setStyleSheet("background-color: rgba(16, 30, 41, 240);\n"
"border-radius: 10px;")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(270, 110, 171, 21))
        font = QtGui.QFont()
        font.setFamily("News706 BT")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(270, 230, 141, 21))
        font = QtGui.QFont()
        font.setFamily("News706 BT")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_8.raise_()
        self.label.raise_()
        self.name_field.raise_()
        self.birthday_field.raise_()
        self.game_field.raise_()
        self.goal_field.raise_()
        self.assist_field.raise_()
        self.penalty_minutes_field.raise_()
        self.insert_button.raise_()
        self.back_to_admin_window.raise_()
        self.label_2.raise_()
        self.label_3.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Add New Player"))
        self.name_field.setPlaceholderText(_translate("Dialog", "Player Name"))
        self.name_field.setFocus()
        self.name_field.show()
        self.birthday_field.setPlaceholderText(_translate("Dialog", "Player Birthday"))
        self.birthday_field.setFocus()
        self.birthday_field.show()
        self.game_field.setPlaceholderText(_translate("Dialog", "Games"))
        self.game_field.setFocus()
        self.game_field.show()
        self.goal_field.setPlaceholderText(_translate("Dialog", "Goals"))
        self.goal_field.setFocus()
        self.goal_field.show()
        self.assist_field.setPlaceholderText(_translate("Dialog", "Assists"))
        self.assist_field.setFocus()
        self.assist_field.show()
        self.penalty_minutes_field.setPlaceholderText(_translate("Dialog", "Penalty Minutes"))
        self.penalty_minutes_field.setFocus()
        self.penalty_minutes_field.show()
        self.insert_button.setText(_translate("Dialog", "add"))
        self.back_to_admin_window.setText(_translate("Dialog", "Admin Window"))
        self.label_2.setText(_translate("Dialog", "Player Main Date"))

        self.label_3.setText(_translate("Dialog", "Player Statistic"))
