# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\kursach_project_gomel\forms\ui\loginWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(750, 500)
        self.logIn_button = QtWidgets.QPushButton(Dialog)
        self.logIn_button.setGeometry(QtCore.QRect(230, 350, 260, 40))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.logIn_button.setFont(font)
        self.logIn_button.setAutoFillBackground(False)
        self.logIn_button.setStyleSheet("QPushButton#pushButton{\n"
"background-color: rgba(2, 65, 118, 255);\n"
"color: rgba(255, 255, 255, 200);\n"
"border-radius: 5px; \n"
"}\n"
"QPushButton#pushButton:pressed{\n"
"padding-left: 5px;\n"
"padding-top: 5px;\n"
"background-color: rgba(2, 65, 118, 255);\n"
"background-position: calc(100% - 10px)center;\n"
"}\n"
"QPushButton#pushButton{\n"
"background-color: rgba(2, 65, 118, 200);\n"
"}")
        self.logIn_button.setObjectName("logIn_button")
        self.username_field = QtWidgets.QLineEdit(Dialog)
        self.username_field.setGeometry(QtCore.QRect(230, 190, 261, 41))
        self.username_field.setStyleSheet("background-color: rgba(0, 0, 0 0);\n"
"font: 14pt \"MS UI Gothic\";\n"
"border:1px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:rgba(46, 82, 101, 255);\n"
"color:rgb(255, 255, 255);\n"
"padding-bottom:7px")
        self.username_field.setObjectName("username_field")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(180, 150, 47, 13))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.password_field = QtWidgets.QLineEdit(Dialog)
        self.password_field.setGeometry(QtCore.QRect(230, 260, 260, 41))
        self.password_field.setStyleSheet("background-color: rgba(0, 0, 0 0);\n"
"font: 14pt \"MS UI Gothic\";\n"
"border: 1px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color: rgba(46, 82, 101, 225);\n"
"color: rgb(255, 255, 255);\n"
"padding-bottom: 7px;")
        self.password_field.setObjectName("password_field")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(180, 220, 47, 13))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.error_field = QtWidgets.QLabel(Dialog)
        self.error_field.setGeometry(QtCore.QRect(230, 320, 251, 20))
        self.error_field.setStyleSheet("font: 75 11pt \"News701 BT\"; color: red;")
        self.error_field.setText("")
        self.error_field.setObjectName("error_field")
        self.back_to_main_window = QtWidgets.QPushButton(Dialog)
        self.back_to_main_window.setGeometry(QtCore.QRect(40, 30, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.back_to_main_window.setFont(font)
        self.back_to_main_window.setStyleSheet("QPushButton#pushButton{\\nbackground-color: rgba(2, 65, 118, 255);\\ncolor: rgba(255, 255, 255, 200);\\nborder-radius: 5px; \\n}\\nQPushButton#pushButton:pressed{\\npadding-left: 5px;\\npadding-top: 5px;\\nbackground-color: rgba(2, 65, 118, 255);\\nbackground-position: calc(100% - 10px)center;\\n}\\nQPushButton#pushButton{\\nbackground-color: rgba(2, 65, 118, 200);\\n}")
        self.back_to_main_window.setObjectName("back_to_main_window")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(20, 10, 691, 451))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: rgba(16, 30, 41, 240);\n"
"border-radius: 10px;")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(300, 40, 120, 120))
        self.label.setStyleSheet("background-image: url(:/newPrefix/pngwing.com (2).png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_5.raise_()
        self.logIn_button.raise_()
        self.username_field.raise_()
        self.label_3.raise_()
        self.password_field.raise_()
        self.label_4.raise_()
        self.error_field.raise_()
        self.back_to_main_window.raise_()
        self.label.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.logIn_button.setText(_translate("Dialog", "Log in"))
        self.username_field.setPlaceholderText(_translate("Dialog", "User Name"))
        self.password_field.setPlaceholderText(_translate("Dialog", "Password"))
        self.back_to_main_window.setText(_translate("Dialog", "Main Window"))
import forms.py.res_rc
