# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\kursach_project_gomel\forms\ui\registrationWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegistrationWindow(object):
    def setupUi(self, RegistrationWindow):
        RegistrationWindow.setObjectName("RegistrationWindow")
        RegistrationWindow.resize(750, 500)
        RegistrationWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        RegistrationWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.register_user_button = QtWidgets.QPushButton(RegistrationWindow)
        self.register_user_button.setGeometry(QtCore.QRect(250, 380, 260, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.register_user_button.setFont(font)
        self.register_user_button.setStyleSheet("QPushButton#pushButton{\n"
"background-color: rgba(2, 65, 118, 255);\n"
"color: rgba(255, 255, 255, 200);\n"
"border-radius: 5px; \n"
"}\n"
"QPushButton#pushButton:pressed{\n"
"padding-left: 5px;\n"
"padding-top: 5px;\n"
"background-color: rgba(2, 65, 118, 255);\n"
"background-position: calc(100% - 10px)center;\n"
"}\n"
"QPushButton#pushButton{\n"
"background-color: rgba(2, 65, 118, 200);\n"
"}")
        self.register_user_button.setObjectName("register_user_button")
        self.back_to_main_window = QtWidgets.QPushButton(RegistrationWindow)
        self.back_to_main_window.setGeometry(QtCore.QRect(40, 30, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.back_to_main_window.setFont(font)
        self.back_to_main_window.setObjectName("back_to_main_window")
        self.check_is_superuser = QtWidgets.QCheckBox(RegistrationWindow)
        self.check_is_superuser.setGeometry(QtCore.QRect(250, 310, 171, 31))
        self.check_is_superuser.setStyleSheet("background-color: rgba(0, 0, 0 0);\n"
"font: 14pt \"MS UI Gothic\";\n"
"border:1px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:rgba(46, 82, 101, 255);\n"
"color:rgb(255, 255, 255);\n"
"padding-bottom:7px")
        self.check_is_superuser.setIconSize(QtCore.QSize(20, 20))
        self.check_is_superuser.setCheckable(True)
        self.check_is_superuser.setObjectName("check_is_superuser")
        self.username_field = QtWidgets.QLineEdit(RegistrationWindow)
        self.username_field.setGeometry(QtCore.QRect(250, 130, 261, 41))
        self.username_field.setStyleSheet("background-color: rgba(0, 0, 0 0);\n"
"font: 14pt \"MS UI Gothic\";\n"
"border:1px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:rgba(46, 82, 101, 255);\n"
"color:rgb(255, 255, 255);\n"
"padding-bottom:7px")
        self.username_field.setText("")
        self.username_field.setObjectName("username_field")
        self.password1_field = QtWidgets.QLineEdit(RegistrationWindow)
        self.password1_field.setGeometry(QtCore.QRect(250, 190, 260, 41))
        self.password1_field.setStyleSheet("background-color: rgba(0, 0, 0 0);\n"
"font: 14pt \"MS UI Gothic\";\n"
"border:1px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:rgba(46, 82, 101, 255);\n"
"color:rgb(255, 255, 255);\n"
"padding-bottom:7px")
        self.password1_field.setText("")
        self.password1_field.setObjectName("password1_field")
        self.password2_field = QtWidgets.QLineEdit(RegistrationWindow)
        self.password2_field.setGeometry(QtCore.QRect(250, 250, 260, 41))
        self.password2_field.setStyleSheet("background-color: rgba(0, 0, 0 0);\n"
"font: 14pt \"MS UI Gothic\";\n"
"border:1px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:rgba(46, 82, 101, 255);\n"
"color:rgb(255, 255, 255);\n"
"padding-bottom:7px")
        self.password2_field.setText("")
        self.password2_field.setObjectName("password2_field")
        self.label_4 = QtWidgets.QLabel(RegistrationWindow)
        self.label_4.setGeometry(QtCore.QRect(20, 10, 691, 450))
        self.label_4.setStyleSheet("background-color: rgba(16, 30, 41, 240);\n"
"border-radius: 10px;")
        self.label_4.setText("")
        self.label_4.setWordWrap(False)
        self.label_4.setIndent(0)
        self.label_4.setObjectName("label_4")
        self.error_field = QtWidgets.QLabel(RegistrationWindow)
        self.error_field.setGeometry(QtCore.QRect(250, 350, 251, 20))
        self.error_field.setStyleSheet("font: 75 11pt \"News701 BT\"; color: red;")
        self.error_field.setText("")
        self.error_field.setObjectName("error_field")
        self.label_4.raise_()
        self.register_user_button.raise_()
        self.back_to_main_window.raise_()
        self.check_is_superuser.raise_()
        self.username_field.raise_()
        self.password1_field.raise_()
        self.password2_field.raise_()
        self.error_field.raise_()

        self.retranslateUi(RegistrationWindow)
        QtCore.QMetaObject.connectSlotsByName(RegistrationWindow)

    def retranslateUi(self, RegistrationWindow):
        _translate = QtCore.QCoreApplication.translate
        RegistrationWindow.setWindowTitle(_translate("RegistrationWindow", "Dialog"))
        self.register_user_button.setText(_translate("RegistrationWindow", "Register"))
        self.back_to_main_window.setText(_translate("RegistrationWindow", "Admin Window"))
        self.check_is_superuser.setText(_translate("RegistrationWindow", "is_superuser"))
        self.username_field.setPlaceholderText(_translate("RegistrationWindow", "User Name"))
        self.password1_field.setPlaceholderText(_translate("RegistrationWindow", "Password"))
        self.password2_field.setPlaceholderText(_translate("RegistrationWindow", "Confirm Password"))
